### ISSUE TITLE
Question(s): how exactly do I know if this is working and can I see Gravatars on messages?

### ISSUE THREAD

**Issue by GwynethLlewelyn** [prodrigestivill/roundcube-gravatar#2]
Hi,

I activated the plugin and got no errors; then I went to the Address Book, checked the box for Gravatars, added a new contact which I was 100% sure that it had a Gravatar... but nothing happened. To be honest, I don't know what to expect — is there some 'magic' I have to do so that Gravatars 'appear'?

Uploading any kind of image works well, even animated GIFs (and they get redimensioned as expected), so I'm pretty sure the graphics subsystem works.

There are no errors on any logs.

Also, and this is a different question... will the Gravatars also show up on messages that come from addresses that are _not_ in the Address Book yet?

**Comment by paspo** [comment]
Try to check the message preview.

Also, AFAIK, this is not working with the default skin, you should use "larry" skin.

Be sure to have 

> $config['gravatar_enabled'] = true; 

in `plugins/gravatar/config.inc.php`

**Comment by prodrigestivill** [comment]
@GwynethLlewelyn It should show the Gravatar from the sender when you looking the e-mails in the Mail tab. It will show Gravatar as long as you don't have the contact saved or the saved one don't have any picture saved (if it has a picture it will show the one from your addressbook instead, if you have ensured it is always the latest plugin in roundcube configuration). It can't be seen on the Addressbook tab nor the contact editing window, because it gets not mixed with the Personal or others Adressbooks, it just complete information of the contact when queried by the Inbox or Contact viewer.

@paspo It has been tested with the default skin in roundcube 1.2.0.
It should not depend of the skin as long as the skin supports displaying contacts avatars in Inbox, since it acts as a contact AddressBook provider. But if you find an issue with some skin, please report it as a separated issue with all the details you can provide (list of plugins and its order in config file, version of roundcube and its plugins, ...). Thanks in advance.
